title: Preludens
tagline: Find the Game
description: >-
  Preludens bereidt een brede doelgroep voor op verandering met MicroGame Stories,
  Short Stories en interactieve leerervaringen in de eigen leeromgeving.
url: "https://preludens.github.io"
baseurl: "/preludens-website"
lang: nl
email: info@preludens.nl

permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - .bundle
  - node_modules

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections:
  verhalen:
    output: true
    permalink: /verhalen/:name/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
  - scope:
      path: ""
      type: "verhalen"
    values:
      layout: verhaal

social:
  email: info@preludens.nl
